import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const universities = [
  {
    name: "University of Oxford",
    country: "UK",
    location: "Oxford, England",
    tuitionFee: 33000,
    ranking: 1,
    establishedYear: 1096,
    acceptanceRate: 17,
    minIeltsScore: 7.5,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "Harvard University",
    country: "USA",
    location: "Cambridge, Massachusetts",
    tuitionFee: 54000,
    ranking: 2,
    establishedYear: 1636,
    acceptanceRate: 4,
    minIeltsScore: 7.5,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "University of Toronto",
    country: "Canada",
    location: "Toronto, Ontario",
    tuitionFee: 45000,
    ranking: 21,
    establishedYear: 1827,
    acceptanceRate: 43,
    minIeltsScore: 6.5,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "University of Melbourne",
    country: "Australia",
    location: "Melbourne, Victoria",
    tuitionFee: 42000,
    ranking: 33,
    establishedYear: 1853,
    acceptanceRate: 70,
    minIeltsScore: 6.5,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "MIT",
    country: "USA",
    location: "Cambridge, Massachusetts",
    tuitionFee: 55000,
    ranking: 3,
    establishedYear: 1861,
    acceptanceRate: 7,
    minIeltsScore: 7.0,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "University of Cambridge",
    country: "UK",
    location: "Cambridge, England",
    tuitionFee: 35000,
    ranking: 4,
    establishedYear: 1209,
    acceptanceRate: 21,
    minIeltsScore: 7.5,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "Stanford University",
    country: "USA",
    location: "Stanford, California",
    tuitionFee: 56000,
    ranking: 5,
    establishedYear: 1885,
    acceptanceRate: 4,
    minIeltsScore: 7.0,
    hasScholarships: true,
    campusType: "Suburban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "University of Sydney",
    country: "Australia",
    location: "Sydney, NSW",
    tuitionFee: 46000,
    ranking: 41,
    establishedYear: 1850,
    acceptanceRate: 30,
    minIeltsScore: 6.5,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "UBC",
    country: "Canada",
    location: "Vancouver, BC",
    tuitionFee: 41000,
    ranking: 47,
    establishedYear: 1908,
    acceptanceRate: 52,
    minIeltsScore: 6.5,
    hasScholarships: true,
    campusType: "Suburban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "Imperial College London",
    country: "UK",
    location: "London, England",
    tuitionFee: 36000,
    ranking: 7,
    establishedYear: 1907,
    acceptanceRate: 14,
    minIeltsScore: 7.0,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "UCL",
    country: "UK",
    location: "London, England",
    tuitionFee: 32000,
    ranking: 8,
    establishedYear: 1826,
    acceptanceRate: 48,
    minIeltsScore: 6.5,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "McGill University",
    country: "Canada",
    location: "Montreal, Quebec",
    tuitionFee: 28000,
    ranking: 31,
    establishedYear: 1821,
    acceptanceRate: 46,
    minIeltsScore: 6.5,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "Caltech",
    country: "USA",
    location: "Pasadena, California",
    tuitionFee: 58000,
    ranking: 6,
    establishedYear: 1891,
    acceptanceRate: 6,
    minIeltsScore: 7.0,
    hasScholarships: true,
    campusType: "Suburban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "UC Berkeley",
    country: "USA",
    location: "Berkeley, California",
    tuitionFee: 44000,
    ranking: 27,
    establishedYear: 1868,
    acceptanceRate: 14,
    minIeltsScore: 6.5,
    hasScholarships: false,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "University of Edinburgh",
    country: "UK",
    location: "Edinburgh, Scotland",
    tuitionFee: 29000,
    ranking: 15,
    establishedYear: 1582,
    acceptanceRate: 10,
    minIeltsScore: 6.5,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "University of Waterloo",
    country: "Canada",
    location: "Waterloo, Ontario",
    tuitionFee: 38000,
    ranking: 154,
    establishedYear: 1957,
    acceptanceRate: 53,
    minIeltsScore: 6.5,
    hasScholarships: true,
    campusType: "Suburban",
    courseTypes: ["Undergraduate", "Postgraduate"],
  },
  {
    name: "Australian National University",
    country: "Australia",
    location: "Canberra, ACT",
    tuitionFee: 39000,
    ranking: 30,
    establishedYear: 1946,
    acceptanceRate: 35,
    minIeltsScore: 6.5,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "King's College London",
    country: "UK",
    location: "London, England",
    tuitionFee: 30000,
    ranking: 37,
    establishedYear: 1829,
    acceptanceRate: 13,
    minIeltsScore: 7.0,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "University of New South Wales",
    country: "Australia",
    location: "Sydney, NSW",
    tuitionFee: 44000,
    ranking: 45,
    establishedYear: 1949,
    acceptanceRate: 35,
    minIeltsScore: 6.5,
    hasScholarships: true,
    campusType: "Urban",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
  {
    name: "Cornell University",
    country: "USA",
    location: "Ithaca, New York",
    tuitionFee: 62000,
    ranking: 20,
    establishedYear: 1865,
    acceptanceRate: 8,
    minIeltsScore: 7.0,
    hasScholarships: true,
    campusType: "Rural",
    courseTypes: ["Undergraduate", "Postgraduate", "PhD"],
  },
];

async function main() {
  console.log("Clearing existing data...");
  await prisma.university.deleteMany({});

  console.log(`Seeding ${universities.length} universities...`);

  for (const uni of universities) {
    await prisma.university.create({
      data: uni,
    });
  }

  console.log("Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
