// // //
import type { Metadata } from "next";
import { Rubik, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/_context/theme-context";
import ModernScroll from "@/_context/modern-scroll";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${rubik.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <ModernScroll>
            <main className="relative z-0 min-h-screen w-full overflow-x-hidden">
              {children}
            </main>
          </ModernScroll>
        </ThemeProvider>
      </body>
    </html>
  );
}
